### ISSUE TITLE
Contributor signup

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/piratey#1]
If you would like to help contribute to this project, please comment on this issue so that I can tag you in the future on other issues and PRs.

**Comment by TechnicalIllusion** [comment]
I am willing to contribute

**Comment by VilimKrajinovic** [comment]
I'd like to contribute

**Comment by arturgawlik** [comment]
hufciamcie here. Wanna help :)

**Comment by cmgriffing** [comment]
Closing all issues as this project is now Archived.
