### ISSUE TITLE
Needed Assets

### ISSUE THREAD

**Issue by cmgriffing** [cmgriffing/piratey#6]
We will most likely need  some assets to get things going more.

This will include:

- [x] - Title Font - Arbutus Slab
- [x] - Body Font - Roboto
- [ ] - Screenshots

**Comment by paulash** [comment]
[Vestigo_logo.zip](https://github.com/cmgriffing/piratey/files/4244944/Vestigo_logo.zip)
Here is the final versions of the logos; including vector versions and an icon [needs to be converted to an actual icon file]

**Comment by cmgriffing** [comment]
Closing all issues as this project is now Archived.
